name: Docker Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - '.github/workflows/docker_build.yml'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest-arm

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile
